mod config;
mod proof;
mod run_dir;
mod steps;

use std::{
    fs,
    path::{Path, PathBuf},
    time::Instant,
};

use anyhow::{Context, Result, bail};
use clap::{ArgGroup, Parser, Subcommand};
use tracing::{error, info, warn};

use proof::{LoadedProof, RunTimeInputs};
use run_dir::{RunDir, StepTiming, cleanup_intermediates, update_latest_symlink, write_summary};

const EXPECTED_PUBLIC_VALUES_LEN: usize = 36;

#[derive(Parser, Debug)]
#[command(author, version, about)]
struct Cli {
    #[command(subcommand)]
    cmd: Cmd,
}

#[derive(Subcommand, Debug)]
enum Cmd {
    /// Generate a v5c boolean circuit. Provide either `--proof` (full pipeline
    /// with cleartext-exec sanity check) or `--vkey` (circuit-only, no sanity
    /// check possible without runtime proof inputs).
    #[command(group(
        ArgGroup::new("source").required(true).args(["proof", "vkey"])
    ))]
    Gen {
        /// Path to a `ProofReceiptWithMetadata` file (zkaleido `.save()` output).
        #[arg(long)]
        proof: Option<PathBuf>,
        /// Path to a binary file containing the 32-byte SP1 program vkey hash
        /// (the raw output of `sp1_sdk::HashableKey::bytes32_raw()`).
        #[arg(long)]
        vkey: Option<PathBuf>,
        /// Parent directory under which a timestamped run dir is created.
        #[arg(long, env = "G16_PIPELINE_RUNS", default_value = "pipeline-runs")]
        runs_dir: PathBuf,
        /// Keep the v5a `g16.ckt` intermediate after success (default: delete it).
        #[arg(long)]
        keep_intermediate: bool,
        /// Skip the cleartext-exec sanity check at the end (only relevant when `--proof` is used).
        #[arg(long)]
        no_sanity_check: bool,
    },
    /// Validate an existing v5c circuit against a fresh proof. Runs only the
    /// input-synthesis + write-input-bits + cleartext-exec stages — skips the
    /// expensive `g16gen generate` + `ckt-lvl prealloc`. Useful when a
    /// `--vkey`-generated circuit needs validating without regeneration.
    Validate {
        /// Path to the v5c circuit to validate.
        #[arg(long)]
        v5c: PathBuf,
        /// Path to a `ProofReceiptWithMetadata` file generated by the same
        /// SP1 program the v5c was built for.
        #[arg(long)]
        proof: PathBuf,
        /// Parent directory under which a timestamped run dir is created.
        #[arg(long, env = "G16_PIPELINE_RUNS", default_value = "pipeline-runs")]
        runs_dir: PathBuf,
    },
}

#[monoio::main]
async fn main() {
    tracing_subscriber::fmt::init();

    let cli = Cli::parse();
    let result = match cli.cmd {
        Cmd::Gen {
            proof,
            vkey,
            runs_dir,
            keep_intermediate,
            no_sanity_check,
        } => run_gen(proof, vkey, runs_dir, keep_intermediate, no_sanity_check).await,
        Cmd::Validate {
            v5c,
            proof,
            runs_dir,
        } => run_validate(v5c, proof, runs_dir).await,
    };

    if let Err(e) = result {
        error!("{e:#}");
        std::process::exit(1);
    }
}

async fn run_gen(
    proof_path: Option<PathBuf>,
    vkey_path: Option<PathBuf>,
    runs_dir: PathBuf,
    keep_intermediate: bool,
    no_sanity_check: bool,
) -> Result<()> {
    let total_start = Instant::now();

    let source_label = match (&proof_path, &vkey_path) {
        (Some(p), None) => fs::canonicalize(p)
            .with_context(|| format!("failed to resolve --proof {:?}", p))?
            .display()
            .to_string(),
        (None, Some(p)) => fs::canonicalize(p)
            .with_context(|| format!("failed to resolve --vkey {:?}", p))?
            .display()
            .to_string(),
        _ => unreachable!("clap ArgGroup guarantees exactly one"),
    };

    let runs_dir = prepare_runs_dir(&runs_dir)?;
    let run = RunDir::create(&runs_dir)?;
    info!(run_dir = ?run.root, "created run directory");

    let mut timings: Vec<StepTiming> = Vec::new();

    let success = match drive_gen(
        proof_path.as_deref(),
        vkey_path.as_deref(),
        &run,
        &mut timings,
        no_sanity_check,
    )
    .await
    {
        Ok(()) => true,
        Err(e) => {
            error!(error = %e, "pipeline failed");
            let _ = write_summary(&run, &source_label, &timings, total_start.elapsed(), false);
            return Err(e);
        }
    };

    cleanup_intermediates(&run, keep_intermediate)?;
    write_summary(
        &run,
        &source_label,
        &timings,
        total_start.elapsed(),
        success,
    )?;
    update_latest_symlink(&runs_dir, &run)?;

    info!(v5c = ?run.v5c_ckt(), "pipeline completed");
    Ok(())
}

async fn run_validate(v5c_path: PathBuf, proof_path: PathBuf, runs_dir: PathBuf) -> Result<()> {
    let total_start = Instant::now();

    let v5c_path = fs::canonicalize(&v5c_path)
        .with_context(|| format!("failed to resolve --v5c {:?}", v5c_path))?;
    let proof_path = fs::canonicalize(&proof_path)
        .with_context(|| format!("failed to resolve --proof {:?}", proof_path))?;

    let runs_dir = prepare_runs_dir(&runs_dir)?;
    let run = RunDir::create(&runs_dir)?;
    info!(run_dir = ?run.root, "created run directory");

    let source_label = format!("v5c={}, proof={}", v5c_path.display(), proof_path.display());
    let mut timings: Vec<StepTiming> = Vec::new();

    let success = match drive_validate(&v5c_path, &proof_path, &run, &mut timings).await {
        Ok(()) => true,
        Err(e) => {
            error!(error = %e, "validate failed");
            let _ = write_summary(&run, &source_label, &timings, total_start.elapsed(), false);
            return Err(e);
        }
    };

    write_summary(
        &run,
        &source_label,
        &timings,
        total_start.elapsed(),
        success,
    )?;
    update_latest_symlink(&runs_dir, &run)?;

    info!(v5c = ?v5c_path, "validation passed");
    Ok(())
}

async fn drive_gen(
    proof_path: Option<&Path>,
    vkey_path: Option<&Path>,
    run: &RunDir,
    timings: &mut Vec<StepTiming>,
    no_sanity_check: bool,
) -> Result<()> {
    let t = Instant::now();
    let loaded: LoadedProof = match (proof_path, vkey_path) {
        (Some(p), None) => proof::load_from_proof(p)?,
        (None, Some(p)) => proof::load_from_vkey_file(p)?,
        _ => unreachable!("clap ArgGroup guarantees exactly one"),
    };
    if let Some(rt) = &loaded.run_time {
        check_pv_len(rt)?;
    }
    config::write_compile_time_json(&run.compile_time_json(), &loaded.compile_time)?;
    timings.push(StepTiming {
        name: "synth-configs",
        duration: t.elapsed(),
    });

    let will_validate = loaded.run_time.is_some() && !no_sanity_check;
    let total_steps = if will_validate { 4 } else { 2 };

    let t = Instant::now();
    info!("step 1/{total_steps}: g16gen generate");
    steps::run_g16gen("generate", &run.compile_time_json(), &run.root)?;
    if !run.v5a_ckt().exists() {
        bail!("g16gen generated no v5a at {:?}", run.v5a_ckt());
    }
    timings.push(StepTiming {
        name: "g16gen-generate",
        duration: t.elapsed(),
    });

    let t = Instant::now();
    info!("step 2/{total_steps}: ckt-lvl prealloc");
    steps::prealloc_v5c(&run.v5a_ckt(), &run.v5c_ckt()).await?;
    timings.push(StepTiming {
        name: "ckt-lvl-prealloc",
        duration: t.elapsed(),
    });

    match (&loaded.run_time, no_sanity_check) {
        (Some(rt), false) => {
            info!("step 3/{total_steps}: g16gen write-input-bits");
            step_write_input_bits(rt, run, timings)?;
            info!("step 4/{total_steps}: cleartext exec sanity check");
            step_sanity_check(&run.v5c_ckt(), &run.inputs_txt(), timings).await?;
        }
        (Some(_), true) => info!("sanity check skipped (--no-sanity-check)"),
        (None, _) => warn!(
            "v5c emitted from --vkey alone is unvalidated; rerun `validate` once a proof is \
             available to assert the verifier accepts it"
        ),
    }

    Ok(())
}

async fn drive_validate(
    v5c_path: &Path,
    proof_path: &Path,
    run: &RunDir,
    timings: &mut Vec<StepTiming>,
) -> Result<()> {
    let loaded = proof::load_from_proof(proof_path)?;
    let run_time = loaded
        .run_time
        .as_ref()
        .expect("load_from_proof always populates run_time");
    check_pv_len(run_time)?;

    info!("step 1/2: g16gen write-input-bits");
    step_write_input_bits(run_time, run, timings)?;
    info!("step 2/2: cleartext exec sanity check");
    step_sanity_check(v5c_path, &run.inputs_txt(), timings).await?;

    Ok(())
}

// ---- helpers shared by drive_gen and drive_validate ----

fn check_pv_len(run_time: &RunTimeInputs) -> Result<()> {
    if run_time.public_values.len() != EXPECTED_PUBLIC_VALUES_LEN {
        bail!(
            "public values length {} != {} expected by g16gen (hardcoded \
             INPUT_MESSAGE_LEN at g16/g16gen/src/circuit_args.rs); this pipeline \
             currently supports only 36-byte programs",
            run_time.public_values.len(),
            EXPECTED_PUBLIC_VALUES_LEN,
        );
    }
    Ok(())
}

fn step_write_input_bits(
    run_time: &RunTimeInputs,
    run: &RunDir,
    timings: &mut Vec<StepTiming>,
) -> Result<()> {
    config::write_run_time_json(&run.run_time_json(), run_time)?;
    let t = Instant::now();
    steps::run_g16gen("write-input-bits", &run.run_time_json(), &run.root)?;
    if !run.inputs_txt().exists() {
        bail!("g16gen produced no inputs.txt at {:?}", run.inputs_txt());
    }
    timings.push(StepTiming {
        name: "g16gen-inputs",
        duration: t.elapsed(),
    });
    Ok(())
}

async fn step_sanity_check(v5c: &Path, inputs: &Path, timings: &mut Vec<StepTiming>) -> Result<()> {
    let t = Instant::now();
    steps::sanity_check(v5c, inputs).await?;
    timings.push(StepTiming {
        name: "sanity-check",
        duration: t.elapsed(),
    });
    Ok(())
}

fn prepare_runs_dir(runs_dir: &Path) -> Result<PathBuf> {
    fs::create_dir_all(runs_dir)
        .with_context(|| format!("failed to create --runs-dir {:?}", runs_dir))?;
    fs::canonicalize(runs_dir)
        .with_context(|| format!("failed to resolve --runs-dir {:?}", runs_dir))
}
